## AI4Climate ML tutorial - Training in PyTorch
* Author: Stephen Haddad
* Affiliation: UK Met Office
* History: 1.0
* Last update: 2026-02-10
* © British Crown Copyright 2017-2065, Met Office. Please see LICENSE.md for license details.

## Overview of the broad topic covered

In this notebook, we will use the previously prepared tabular dataset to predict climate zones. We will train on different eras to see how well the results generalise with climate change.

### Prerequisites 
- Same as previous  notebooks
- Have completed training pipeline, inference and evaluation notebooks.

### Learning outcomes from completing the notebook

- Understand how to build a pipeline using pytorch
- Understand the core pytorch concepts and classes
- Understand bho to manage experiments using ML Flow

## Tutorial - Creating a machine learning pipe

Further Reading
* [PyTorch Docs](https://pytorch.org/)

## Setup
First we start by loading the data we have prepared previously, and other set up elements

### Environment 
This notebook uses the environment defined in this repository in the [requirements.txt](../requirements.txt) file (venv) or [requirements.yaml](../requirements.yaml).

### Imports

In [1]:
import pathlib
import os
import datetime
import json

In [2]:
import numpy 
import pandas

In [3]:
import matplotlib
import matplotlib.pyplot

In [4]:
import sklearn
import sklearn.preprocessing
import sklearn.tree

In [5]:
import mlflow

In [6]:
import torch

## Load and prepare data 
We will now load the dataset and do the usual data prep steps, like train/test split and normalisation.

#### Dataset parameters

In [7]:
with open ('config.json','r') as tutorial_config:
    tutorial_config = json.load(tutorial_config)
tutorial_config

{'platform': 'jasmin',
 'default_dirs': {'mo_linux': '/data/users/dscop/ml_tutorial/',
  'jasmin': '/gws/nopw/j04/mohc_shared/dscop/'},
 'random_seed': 12345,
 'climate_subgroups': {'non-land': 'None',
  'Af': 'Tropical, rainforest',
  'Am': 'Tropical, monsoon',
  'Aw': 'Tropical, savannah',
  'BWh': 'Arid, desert, hot',
  'BWk': 'Arid, desert, cold',
  'BSh': 'Arid, steppe, hot',
  'BSk': 'Arid, steppe, cold',
  'Csa': 'Temperate, dry summer, hot summer',
  'Csb': 'Temperate, dry summer, warm summer',
  'Csc': 'Temperate, dry summer, cold summer',
  'Cwa': 'Temperate, dry winter, hot summer',
  'Cwb': 'Temperate, dry winter, warm summer',
  'Cwc': 'Temperate, dry winter, cold summer',
  'Cfa': 'Temperate, no dry season, hot summer',
  'Cfb': 'Temperate, no dry season, warm summer',
  'Cfc': 'Temperate, no dry season, cold summer',
  'Dsa': 'Cold, dry summer, hot summer',
  'Dsb': 'Cold, dry summer, warm summer',
  'Dsc': 'Cold, dry summer, cold summer',
  'Dsd': 'Cold, dry summer, very cold winter',
  'Dwa': 'Cold, dry winter, hot summer',
  'Dwb': 'Cold, dry winter, warm summer',
  'Dwc': 'Cold, dry winter, cold summer',
  'Dwd': 'Cold, dry winter, very cold winter',
  'Dfa': 'Cold, no dry season, hot summer',
  'Dfb': 'Cold, no dry season, warm summer',
  'Dfc': 'Cold, no dry season, cold summer',
  'Dfd': ',Cold, no dry season, very cold winter',
  'ET': 'Polar, tundra',
  'EF': 'Polar, frost'},
 'resolutions_names': {'0.1': '0p1', '0.5': '0p5', '1.0': '1p0'},
 'dataset_prefix': {'climate_mean': 'ensemble_mean',
  'climate_std': 'ensemble_std',
  'climate_zone': 'koppen_geiger'},
 'fname_template': '{prefix}_{res}.{suffix}',
 'time_dir_template': '{start_year}_{end_year}',
 'csv_out_template': 'climate_zones_{resolution}.csv',
 'future_scenarios': ['ssp119',
  'ssp126',
  'ssp245',
  'ssp370',
  'ssp434',
  'ssp460',
  'ssp585'],
 'historic_scenarios': ['historic']}

In [8]:
def get_platform_dir(select_platform, config):
    try:
        root_path = pathlib.Path(config['default_dirs'][select_platform]) / 'climate_zones'
    except KeyError:
        root_path = pathlib.Path(os.environ['HOME']) / 'climate_zones'
    return root_path

In [9]:
current_platform = tutorial_config['platform']

In [10]:
current_platform

'jasmin'

In [11]:
root_data_dir = get_platform_dir(current_platform, tutorial_config)

print(root_data_dir.is_dir())
root_data_dir

True

PosixPath('/gws/nopw/j04/mohc_shared/dscop/climate_zones')

In [12]:
ml_ready_dir = root_data_dir / 'ml_ready'
print(ml_ready_dir.is_dir())
ml_ready_dir

True

PosixPath('/gws/nopw/j04/mohc_shared/dscop/climate_zones/ml_ready')

In [13]:
resolutions_dict = {float(k1): v1 for k1,v1 in tutorial_config['resolutions_names'].items()}

dataset_prefix_dict = tutorial_config['dataset_prefix']

format_str = 'nc'
historic_scenario_str = 'historic'

future_scenario_list = tutorial_config['future_scenarios']
historic_scenario_list = tutorial_config['historic_scenarios']

time_periods = { 
    (1901,1930): historic_scenario_list, 
    (1931,1960): historic_scenario_list,
    (1961,1990): historic_scenario_list,
    (1991,2020): historic_scenario_list,
    (2041,2070): future_scenario_list,
    (2071,2099): future_scenario_list,
}

In [14]:
fname_template = tutorial_config['fname_template']
time_dir_template = tutorial_config['time_dir_template']
ml_ready_fname_template = tutorial_config['csv_out_template']

#### Load data for training

In [15]:
current_res = 1.0

In [16]:
mlready_data_path = ml_ready_dir / ml_ready_fname_template.format(resolution=resolutions_dict[current_res])
print(mlready_data_path.is_file())
mlready_data_path

True

PosixPath('/gws/nopw/j04/mohc_shared/dscop/climate_zones/ml_ready/climate_zones_1p0.csv')

In [17]:
zones_df = pandas.read_csv(mlready_data_path)

We have two options for the target. We have the full 30 class climate subgroups of the Koppen-Geiger classification data from the original dataset. We also have the processed five class climate group target, which presents an easier target for our classification algorithm to predict.

#### Selecting features

In [18]:
predictors_dict = {
    'precip_mean': [c1 for c1 in zones_df.columns if 'precipitation' in c1 and 'mean' in c1],
    'precip_std': [c1 for c1 in zones_df.columns if 'precipitation' in c1 and 'std' in c1],
    'temp_mean': [c1 for c1 in zones_df.columns if 'air_temperature' in c1 and 'mean' in c1],
    'temp_std': [c1 for c1 in zones_df.columns if 'air_temperature' in c1 and 'std' in c1],
}

In [19]:
target_var = 'climate_group' # 5 classes
# target_var = 'climate_subgroup # 30 classes

In [20]:
predictors = predictors_dict['precip_mean'] + predictors_dict['temp_mean']
predictors

['precipitation_1.0_mean',
 'precipitation_2.0_mean',
 'precipitation_3.0_mean',
 'precipitation_4.0_mean',
 'precipitation_5.0_mean',
 'precipitation_6.0_mean',
 'precipitation_7.0_mean',
 'precipitation_8.0_mean',
 'precipitation_9.0_mean',
 'precipitation_10.0_mean',
 'precipitation_11.0_mean',
 'precipitation_12.0_mean',
 'air_temperature_1.0_mean',
 'air_temperature_2.0_mean',
 'air_temperature_3.0_mean',
 'air_temperature_4.0_mean',
 'air_temperature_5.0_mean',
 'air_temperature_6.0_mean',
 'air_temperature_7.0_mean',
 'air_temperature_8.0_mean',
 'air_temperature_9.0_mean',
 'air_temperature_10.0_mean',
 'air_temperature_11.0_mean',
 'air_temperature_12.0_mean']

#### Train/test split

In [21]:
random_seed = tutorial_config['random_seed']

In [22]:
test_frac = 0.1
val_frac = 0.1
val_frac_sub = (val_frac / (1.0-test_frac) )

In [23]:
test_df = zones_df.groupby(['period_start','scenario']).sample(frac=test_frac, random_state=random_seed)
remain_df = zones_df.drop(test_df.index)

In [24]:
val_df = remain_df.groupby(['period_start','scenario']).sample(frac=val_frac_sub, random_state=random_seed)
train_df = remain_df.drop(val_df.index)

## Using Pytorch

From this point in the tutorial, we diverge from what was done in the ml training pipeline tutorial as instead of setting up and training our model in scikit-learn, we're going to use a more sophisticated machine learning library called pytorch. This gives us more more control over how we implement our neural network and gives us much more power to use advanced architectures, losss functions and distributed computing techniques.

When using pytorch, the main difference is that we will specify the details of the nerual netowrk architecture and training loop much more explictly. This means we can customise and optimise these details for the particular problem. Key elements of a pytorch training pipeline, compared to what was previous described are as follows:
1. Data Loading and Cleaning - This is usually done through a pytorch Dataset class. In addition one creates a Dataset Loader object, which whas the responsibility for iterating through the data in the dataset, including shuffling data between epoch where appropriate.
2. Feature Engineering - Same as before, but may be a part of the dataset class
3. Train/test split - Same method as before. Usually different dataset objects will represent the train, validate and test sets.
4. Data Preparation - Same as before, but code may be structured differently to have the normalisation and scaling happening inside the pytorch dataset class.
5. Algorithm Setup - Usuall one creates a class representing the model architecture. One then also speciied key hyperparameters such as the optimiser for training the weights, the learning rate and similar. 
6. Algorithm Training - The elements of the training loop are described more explictly in pytorch typically with a explicit loop for iterating through batches and an outer loop for iterating through batches.
7. Inference - The model object is used as a callable object for producing 
8. Evaluation - Evaluation is the same as before. 
9. Interpretability and Explainability - As model architectures become more complex, it becomes more difficult to explain or interpret the results, this is an active area of research.
10. Model storage - Pytorch has a more sophisticated mechanism for [saving and loading models](https://docs.pytorch.org/tutorials/beginner/saving_loading_models.html).

### Check GPU availability

As a part of this notebook, we will now be training our models using the GPUs on JASMIN. There are some additional steps required for this purpose, such as moving the data and model onto the GPU memory for processing. ML frameworks are especially helpful for this in abtracting away many of the details of this into a few commands.

In this cell, we check whether there is a GPU to use. [CUDA](https://en.wikipedia.org/wiki/CUDA) is the underlying software layer that interfaces to nvidia GPUs. This check allows the notebook to seamlessly work either ion a gpu if one is available or do processing on a cpu when a gpu is not avaiulable.

In [25]:
# Autodetect GPU and use if possible
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

#### Training hyperparameters

In [26]:
training_params = {
    'batch_size': 16,
    'num_epochs': 10,
    'learning_rate': 0.001,
    'loss': 'CrossEntropyLoss',
    'criterion': 'CrossEntropyLoss',
    'optimizer': 'Adam',
}

### Define a data loader

Pytorch defines the interface between the dataset and machine learning through a base class (`torch.utils.data.Dataset), which follow [pythonic paradigms](https://realpython.com/ref/glossary/pythonic/) for software architecture. The implementation of the class hides away the details of the data being used so that the dataset can be used in the generic pytorch architecture. There is also then a data loader is an [iterator](https://www.w3schools.com/python/python_iterators.asp) on the dataset, enabling pytorch to progress through all the data during training. Ultimately the aim of this data architecture is to present the data in the correct [pytorch tensor format](https://docs.pytorch.org/docs/stable/tensors.html) expected by the neural network for training purposes.

Key Concepts:
- **Pytorch Dataset**: Handles loading and preparing the data for use with pytorch. Implements key [python built-in methods](), including:
  - [`__init__`](https://docs.python.org/3/reference/datamodel.html#object.__init__) creates the dataset object, and typically loads and transforms the data ready for use, or in a lazy loading paradigm, define the task pipeline for loading the data upon request.
  - [`__len__`](https://docs.python.org/3/reference/datamodel.html#object.__len__) specifies how many data point there are
  - [`__getitem__`](https://docs.python.org/3/reference/datamodel.html#object.__getitem__) return the item for a particular index
- [**Pytorch Data Loader**](https://docs.pytorch.org/docs/stable/data.html): Interfaces between the ML algorithm being trained and the dataset, selecting mini batches of data to use with each iteration of the gradient descent with back propogation used for training the neural network. Key parameters include:
  - *dataset* - The dataset to load the data from (as described above).
  - [*batch size*](https://www.geeksforgeeks.org/deep-learning/batch-size-in-neural-network/) - How many samples to use in each mini batch during training.
  - [*shuffle*](https://stats.stackexchange.com/questions/245502/why-should-we-shuffle-data-while-training-a-neural-network) - Whether to shuffle the order of data use during each of the epochs. Data shuffling improves the generalisation of what is learned by the neural network.


Further reading
- [Intro to datasets and data loader - pytorch docs](https://docs.pytorch.org/tutorials/beginner/data_loading_tutorial.html)
- [Tutorial on using CSV data with pytorch data architecture - Machine Learning Mastery](https://machinelearningmastery.com/converting-pandas-dataframes-to-pytorch-dataloaders-for-custom-deep-learning-model-training/)
- [Converting pnadas dataframe to the pytorch](https://www.geeksforgeeks.org/deep-learning/converting-a-pandas-dataframe-to-a-pytorch-tensor/)
- [Encoding target data for a neural network using LabelBinarizer - scikit learn](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelBinarizer.html)

### Implementation details for this tutorial

In [27]:
class ClimateZonesDataset(torch.utils.data.Dataset):
    """
    Inspired by this tutorial:
    https://machinelearningmastery.com/converting-pandas-dataframes-to-pytorch-dataloaders-for-custom-deep-learning-model-training/
    """
    def __init__(self, df_ml, predictor_features, target_feature, device, stats_dict=None):
        self._df_ml = df_ml.reset_index().drop(['index'],axis='columns')
        self._device = device
        self.input_scaler = sklearn.preprocessing.StandardScaler()
        if stats_dict is None:
            self.input_scaler.fit(self._df_ml[predictor_features])
        else:
            self.input_scaler.mean_ = numpy.array(stats_dict['input_mean'])
            self.input_scaler.scale_ = numpy.array(stats_dict['input_scale'])

        self._X = torch.tensor(self.input_scaler.transform(self._df_ml[predictor_features]),  
                               dtype=torch.float32)


        self.target_encoder = sklearn.preprocessing.LabelBinarizer(sparse_output=False)
        if stats_dict is None:
            self.target_encoder.fit(self._df_ml[[target_feature]])
        else:
            self.target_encoder.classes_ = numpy.array(stats_dict['target_classes'],dtype='object')

        
        self._y = torch.tensor(self.target_encoder.transform(self._df_ml[[target_feature]]),
                               dtype=torch.float32)

        self.stats_dict = {
            'input_mean': [float(v1) for v1 in self.input_scaler.mean_],
            'input_scale': [float(v1) for v1 in self.input_scaler.scale_],
            'target_classes': list(self.target_encoder.classes_),
        }
        
    def _repr_html_(self):
        return f'''
        <h1>Climate Zones Dataset</h1>
        Number of samples {len(self._X)}
        '''
    
    def __len__(self):
        return len(self._X)

    def __getitem__(self,idx):
        return self._X[idx], self._y[idx]

We now intialise the validate and test set data loaders. Note that we initialise the preprocessing objects with the values learned from the training data, rather than calculating them on the validate or test data.

### Using our dataset class
Once we have defined the class, we can now initialise objects from it. A typical pattern is to define sperate objects for the train, validate and test sets. One then defines an iterator, i.e. a data loader object, for each of the dataset objects. Data loaders are a generic class defined by pytorch that should work with any dataset that complies with the standard interface.

In [28]:
cz_train_ds = ClimateZonesDataset(train_df, predictors, target_var, device)
cz_train_ds

In [29]:
cz_val_ds = ClimateZonesDataset(val_df, predictors, target_var, device, cz_train_ds.stats_dict)
cz_test_ds = ClimateZonesDataset(test_df, predictors, target_var, device, cz_train_ds.stats_dict)

/gws/nopw/j04/mohc_shared/users/shaddad/venv/ai4c_nb_gpu/lib/python3.12/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
/gws/nopw/j04/mohc_shared/users/shaddad/venv/ai4c_nb_gpu/lib/python3.12/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

In [30]:
cz_val_ds[10:13]

(tensor([[-0.4408, -0.3281, -0.1737, -0.2187, -0.2642, -0.3904, -0.3665, -0.3730,
          -0.4555, -0.4177, -0.4437, -0.4373, -0.5886, -0.7146, -0.8674, -0.9889,
          -1.0984, -1.1859, -1.2289, -1.2352, -1.1710, -1.0693, -0.9048, -0.6668],
         [-0.5651, -0.5227, -0.5370, -0.5412, -0.5645, -0.5760, -0.5667, -0.5496,
          -0.6736, -0.6741, -0.6055, -0.5566, -0.9222, -1.0107, -1.1763, -1.3347,
          -1.4611, -1.4826, -1.4871, -1.4774, -1.4484, -1.4140, -1.2316, -0.9931],
         [-0.5389, -0.5087, -0.4206, -0.4052, -0.3257, -0.5483, -0.5183, -0.5140,
          -0.5723, -0.5571, -0.6006, -0.5566, -0.2212, -0.4738, -0.7350, -0.8927,
          -1.0188, -1.0741, -1.1504, -1.2124, -1.1016, -0.9153, -0.5810, -0.2653]]),
 tensor([[0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.]]))

In [31]:
cz_train_loader = torch.utils.data.DataLoader(
        cz_train_ds, batch_size=training_params['batch_size'], shuffle=True, num_workers=1,
    )
cz_val_loader = torch.utils.data.DataLoader(
        cz_val_ds, batch_size=training_params['batch_size'], shuffle=False, num_workers=1,
    )

In [32]:
count = 0
for i1 in cz_train_loader:
    print(i1)
    count +=1
    if count > 5:
        break

[tensor([[-0.6166, -0.6325, -0.6631, -0.6054, -0.2036,  0.3014,  0.9760,  1.4049,
          0.7887,  0.0072, -0.6899, -0.6414,  1.5725,  1.6019,  1.5301,  1.4253,
          1.2566,  1.0305,  0.8985,  0.8783,  1.0183,  1.2681,  1.5617,  1.6201],
        [-0.5203, -0.5124, -0.4935, -0.4917, -0.5952, -0.5833, -0.5624, -0.5233,
         -0.6157, -0.6555, -0.6301, -0.5513, -0.9069, -1.0744, -1.2645, -1.4492,
         -1.5739, -1.5729, -1.5552, -1.5146, -1.4636, -1.4385, -1.2547, -0.9585],
        [-0.5684, -0.5720, -0.5885, -0.6083, -0.6307, -0.6370, -0.6650, -0.7107,
         -0.6953, -0.6770, -0.6458, -0.6131, -0.8794, -1.1989, -1.4974, -1.6416,
         -1.7110, -1.7707, -1.7845, -1.7754, -1.7541, -1.6218, -1.3154, -0.9460],
        [ 3.3721,  3.6299,  2.6508,  0.2427, -0.6335, -0.7005, -0.7207, -0.7750,
         -0.7578, -0.4587,  1.3616,  3.1576,  1.2695,  1.2062,  1.0766,  0.9306,
          0.7524,  0.5662,  0.5144,  0.6071,  0.8037,  1.0505,  1.2176,  1.2625],
        [-0.2651, -0.3383, -0.3176, -0.2469, -0.0367,  0.1549,  0.1931,  0.1964,
          0.0919, -0.1087, -0.1191, -0.1988, -0.4631, -0.2828,  0.0936,  0.3030,
          0.4650,  0.5726,  0.5990,  0.5181,  0.3962,  0.2314, -0.1154, -0.3813],
        [ 2.7045,  2.3900,  1.4011,  0.2310, -0.0777, -0.2667, -0.5146, -0.6139,
         -0.2175,  0.8075,  1.6235,  2.4128,  1.6154,  1.5245,  1.3389,  1.1527,
          0.9227,  0.7811,  0.7250,  0.8203,  1.0118,  1.2485,  1.4807,  1.6201],
        [-0.3437, -0.3495, -0.4411, -0.5325, -0.5393, -0.3359, -0.2269, -0.2591,
         -0.3786, -0.3115, -0.2152, -0.3331, -1.0722, -0.8557, -0.5512, -0.2834,
          0.0647,  0.3533,  0.3966,  0.2966,  0.1274, -0.2478, -0.6735, -1.0307],
        [-0.5946, -0.6064, -0.6232, -0.6510, -0.6820, -0.6696, -0.6975, -0.7200,
         -0.7424, -0.7267, -0.6781, -0.6308, -0.9039, -1.1906, -1.5023, -1.6394,
         -1.7309, -1.7879, -1.8072, -1.7982, -1.7866, -1.6683, -1.3443, -0.9805],
        [-0.5253, -0.5385, -0.5432, -0.5306, -0.4889, -0.4441, -0.2609, -0.2622,
         -0.2411, -0.4265, -0.4996, -0.5195, -1.3538, -1.1713, -0.8404, -0.5308,
         -0.2117,  0.0868,  0.2995,  0.2345,  0.0624, -0.2429, -0.8210, -1.2189],
        [-0.2169, -0.3048, -0.3345, -0.5480, -0.7044, -0.6997, -0.7192, -0.7766,
         -0.7777, -0.7364, -0.6183, -0.4603,  0.7185,  0.8464,  0.9933,  1.0978,
          1.1682,  1.1939,  1.1732,  1.1204,  1.0573,  1.0138,  0.9169,  0.7606],
        [-0.4932, -0.4994, -0.5104, -0.4431, -0.4498, -0.3831, -0.2139, -0.0802,
         -0.0818, -0.2315, -0.4231, -0.4541, -1.0967, -0.9831, -0.7007, -0.4254,
         -0.1586,  0.1168,  0.3553,  0.2738,  0.1101, -0.1084, -0.5434, -0.8895],
        [-0.5287, -0.4752, -0.4056, -0.3984, -0.3798, -0.5043, -0.5211, -0.5031,
         -0.5424, -0.5171, -0.5722, -0.5707, -0.5090, -0.7423, -0.9851, -1.1377,
         -1.2333, -1.2870, -1.3611, -1.3822, -1.3075, -1.1598, -0.8643, -0.5821],
        [-0.3098, -0.3542, -0.4215, -0.4373, -0.5869, -0.5467, -0.4510, -0.4350,
         -0.3994, -0.4616, -0.3594, -0.3693, -1.0661, -0.9471, -0.8576, -0.6430,
         -0.3377, -0.1218, -0.0475, -0.1008, -0.2844, -0.5876, -0.8701, -1.0621],
        [ 1.0051,  0.7526,  0.6790,  0.6604,  0.8166,  0.4918,  0.2870,  0.2762,
          0.5643,  1.0024,  1.4470,  1.2705,  0.1216,  0.1932,  0.3167,  0.3327,
          0.3831,  0.4436,  0.4916,  0.5119,  0.4526,  0.3806,  0.2402,  0.0955],
        [-0.3572,  0.0182,  0.4720,  0.5778,  0.6553,  0.3283,  0.3275,  0.3622,
          0.3987,  0.4283, -0.1182, -0.2827, -0.1447, -0.2164, -0.3526, -0.5033,
         -0.6186, -0.7452, -0.7993, -0.7839, -0.7049, -0.5999, -0.4422, -0.2213],
        [ 1.5011,  1.2665,  1.0636,  0.7371,  0.4501,  0.6546,  0.3752,  0.6287,
          1.5995,  1.8075,  1.5470,  1.6716,  0.2869,  0.3067,  0.3314,  0.3602,
          0.3765,  0.3791,  0.4297,  0.4498,  0.4287,  0.3781,  0.3386,  0.2931]]), tensor([[0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.]])]
[tensor([[-5.9717e-01, -6.0364e-01, -6.1783e-01, -6.0632e-01, -4.8614e-01,
         -2.5611e-01, -1.3223e-01, -3.0404e-01, -5.1073e-01, -6.5554e-01,
         -6.4183e-01, -6.0870e-01, -5.0593e-01, -1.7490e-01,  2.2595e-01,
          4.9079e-01,  6.6177e-01,  7.7683e-01,  8.1385e-01,  7.8097e-01,
          6.3464e-01,  3.6834e-01, -4.3128e-02, -4.3466e-01],
        [ 2.7992e+00,  2.4272e+00,  1.6196e+00,  6.1765e-01, -2.8192e-01,
         -5.7434e-01, -6.9970e-01, -7.0377e-01, -6.2384e-01,  1.6027e-01,
          1.6490e+00,  2.7185e+00,  6.7258e-01,  6.9692e-01,  6.5741e-01,
          5.7782e-01,  5.4014e-01,  5.1671e-01,  5.3501e-01,  5.6569e-01,
          6.2597e-01,  6.6907e-01,  6.7399e-01,  6.3823e-01],
        [-2.7858e-01, -2.9832e-01, -4.4374e-01, -4.5964e-01, -3.7424e-01,
         -7.1361e-02,  1.0271e-01,  1.1506e-01, -1.3157e-01, -2.5689e-01,
         -2.7997e-01, -3.0301e-01, -7.8449e-01, -6.1772e-01, -3.5260e-01,
          3.4980e-02,  3.0575e-01,  5.0811e-01,  5.2468e-01,  4.4977e-01,
          2.8999e-01, -3.2913e-03, -5.0578e-01, -7.6719e-01],
        [-3.8590e-01, -4.2026e-01, -2.0926e-01, -5.6747e-01, -6.0644e-01,
         -5.2550e-01, -4.8934e-01, -3.9932e-01, -4.6277e-01, -5.5807e-01,
         -4.9277e-01, -4.0726e-01, -1.4671e+00, -1.2764e+00, -1.1665e+00,
         -8.9724e-01, -5.9647e-01, -3.9265e-01, -3.3249e-01, -4.1755e-01,
         -6.3558e-01, -9.6660e-01, -1.3125e+00, -1.4542e+00],
        [-4.1886e-01, -4.0909e-01, -3.8068e-01, -3.4696e-01, -3.6670e-02,
         -1.1857e-01, -1.7561e-01, -1.8552e-01,  8.6514e-02, -2.2960e-01,
         -4.1432e-01, -4.4084e-01,  6.1442e-01,  7.3290e-01,  8.1920e-01,
          8.5726e-01,  8.9617e-01,  9.2087e-01,  8.8820e-01,  8.9274e-01,
          8.6875e-01,  8.4022e-01,  7.3760e-01,  6.0058e-01],
        [-3.9858e-01, -3.6720e-01, -4.4374e-01, -5.8106e-01, -4.3112e-01,
         -3.9935e-01,  4.2656e-01, -2.5369e-01, -5.2973e-01, -6.7893e-01,
         -6.6046e-01, -4.8854e-01,  9.3278e-01,  1.0263e+00,  1.1036e+00,
          1.1298e+00,  1.1328e+00,  1.0434e+00,  9.2745e-01,  9.1344e-01,
          9.9013e-01,  1.0798e+00,  1.0875e+00,  9.8958e-01],
        [-3.0478e-01, -3.1787e-01, -3.8512e-01, -4.9947e-01, -4.9360e-01,
         -2.4553e-01, -1.0476e-01, -1.4213e-01, -2.1754e-01, -3.1245e-01,
         -1.5150e-01, -2.6679e-01, -1.1916e+00, -9.3047e-01, -6.0755e-01,
         -3.2462e-01,  2.9332e-02,  3.0388e-01,  3.7803e-01,  2.6347e-01,
          9.4906e-02, -3.0647e-01, -7.8916e-01, -1.1876e+00],
        [-3.2675e-01, -3.5045e-01, -4.6417e-01, -4.6935e-01, -3.9942e-01,
         -1.3973e-01, -6.7897e-02, -1.4313e-02, -8.7229e-02, -2.0621e-01,
         -2.0446e-01, -3.3040e-01, -5.6409e-01, -4.1015e-01, -2.1042e-01,
          1.1057e-01,  3.7430e-01,  5.7045e-01,  6.0523e-01,  5.3050e-01,
          3.6586e-01,  1.0673e-01, -2.8891e-01, -4.8799e-01],
        [-3.8083e-01, -4.0537e-01, -4.5351e-01, -3.3336e-01, -2.8285e-01,
         -1.2670e-01, -1.3905e-03, -2.5988e-01, -4.4829e-01, -3.3097e-01,
         -2.8389e-01, -3.5337e-01, -3.8349e-01, -2.5516e-01,  8.8664e-02,
          4.4727e-01,  6.0206e-01,  6.8869e-01,  6.7752e-01,  6.3814e-01,
          4.9808e-01,  3.3411e-01, -3.1562e-02, -3.1858e-01],
        [-5.3126e-01, -5.1893e-01, -3.9667e-01, -3.4404e-01, -4.2460e-01,
         -5.1899e-01, -5.0741e-01, -4.9151e-01, -4.9173e-01, -4.6060e-01,
         -5.1827e-01, -5.4155e-01, -2.9165e-01, -5.0978e-01, -7.3748e-01,
         -8.7663e-01, -9.9229e-01, -1.0935e+00, -1.1256e+00, -1.1358e+00,
         -1.0518e+00, -9.3237e-01, -6.6482e-01, -3.7819e-01],
        [ 5.0649e-01,  8.9039e-01,  2.2085e+00,  2.7878e+00,  2.1575e+00,
          6.2115e-02, -6.0790e-01, -4.7447e-01,  1.0113e+00,  3.8173e+00,
          3.2886e+00,  1.1238e+00,  1.5236e+00,  1.4525e+00,  1.2923e+00,
          1.1298e+00,  9.7577e-01,  8.2413e-01,  7.3949e-01,  7.7062e-01,
          8.9476e-01,  1.0823e+00,  1.3304e+00,  1.4915e+00],
        [-5.2365e-01, -5.2173e-01, -5.1924e-01, -4.6353e-01, -5.0666e-01,
         -5.4178e-01, -5.6814e-01, -5.9067e-01, -5.6683e-01, -5.2883e-01,
         -5.5161e-01, -5.5481e-01, -9.5745e-02, -3.5479e-01, -6.4433e-01,
         -8.3311e-01, -9.3480e-01, -1.0225e+00, -1.0884e+00, -1.0737e+00,
         -9.8023e-01, -8.3457e-01, -5.0868e-01, -1.8055e-01],
        [-4.0872e-01, -4.4446e-01, -5.1036e-01, -5.3152e-01, -4.2926e-01,
         -1.3484e-01, -7.6571e-02, -1.3051e-01, -1.9582e-01, -2.2570e-01,
         -2.8683e-01, -4.0373e-01, -1.0630e+00, -9.1110e-01, -5.4627e-01,
         -1.9178e-01,  1.1557e-01,  3.8987e-01,  4.6272e-01,  3.8767e-01,
          2.2063e-01, -1.3776e-01, -6.3591e-01, -9.9306e-01],
        [-4.5689e-01, -4.9287e-01, -5.2546e-01, -4.5575e-01, -2.4649e-01,
         -6.1594e-02, -4.7656e-02, -5.0722e-02, -2.3383e-01, -3.2512e-01,
         -4.1039e-01, -4.5409e-01, -1.3998e+00, -1.1270e+00, -5.6343e-01,
         -1.4139e-01,  1.0231e-01,  3.7912e-01,  4.4619e-01,  3.3799e-01,
          1.2092e-01, -2.7224e-01, -1.0205e+00, -1.4354e+00],
        [-2.8450e-01, -3.9327e-01, -5.3523e-01, -5.6455e-01, -5.3090e-01,
         -2.8622e-01, -9.3921e-02, -2.7693e-01, -3.9761e-01, -3.9335e-01,
         -3.6038e-01, -3.8341e-01, -1.5130e+00, -1.2183e+00, -7.7180e-01,
         -3.4982e-01,  6.9136e-02,  3.2323e-01,  3.5944e-01,  2.5726e-01,
          7.3230e-02, -4.0426e-01, -1.1564e+00, -1.5546e+00],
        [-4.9576e-01, -4.1281e-01, -3.2383e-01, -1.8959e-01, -3.7890e-01,
         -4.5714e-01, -3.7513e-01, -4.4426e-01, -5.2973e-01, -5.2590e-01,
         -5.3298e-01, -5.2300e-01, -6.8653e-01, -8.0869e-01, -9.9244e-01,
         -1.1927e+00, -1.3196e+00, -1.3859e+00, -1.3776e+00, -1.3925e+00,
         -1.3401e+00, -1.2649e+00, -1.0292e+00, -7.4209e-01]]), tensor([[0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])]
[tensor([[-0.2896, -0.1736,  0.1878,  0.9304,  1.4563,  1.0282,  0.6001,  0.3537,
          0.6539,  0.4342,  0.1074, -0.1113,  0.2930,  0.4451,  0.6206,  0.7015,
          0.7878,  0.8671,  0.8799,  0.8845,  0.8384,  0.7326,  0.5496,  0.3465],
        [-0.5828, -0.5841, -0.5805, -0.4742, -0.3472,  0.0344,  0.2820,  0.1197,
         -0.4284, -0.5737, -0.6193, -0.5981, -0.6712, -0.4074, -0.0829,  0.2251,
          0.3234,  0.4307,  0.4607,  0.4291,  0.2943,  0.0554, -0.3092, -0.6354],
        [-0.5811, -0.5869, -0.5876, -0.5772, -0.6689, -0.6451, -0.6433, -0.5938,
         -0.7026, -0.7052, -0.6703, -0.5963, -0.9161, -1.1214, -1.3307, -1.5157,
         -1.6292, -1.6202, -1.6193, -1.5891, -1.5351, -1.4898, -1.2807, -0.9774],
        [-0.3597, -0.3914, -0.4766, -0.4810, -0.4143, -0.2284, -0.0997, -0.0794,
         -0.1958, -0.2286, -0.2339, -0.3649, -0.7416, -0.5707, -0.3207,  0.0258,
          0.2947,  0.4952,  0.5371,  0.4643,  0.3030,  0.0383, -0.3988, -0.6511],
        [-0.4713, -0.4743, -0.3141,  0.1766,  2.7599,  4.6459,  3.1099,  3.5654,
          5.9160,  3.5258,  0.2074, -0.3596,  1.2358,  1.2172,  1.1085,  0.9970,
          0.8542,  0.7123,  0.6610,  0.6899,  0.7734,  0.9209,  1.1077,  1.2060],
        [ 1.2307,  0.6372,  0.2704, -0.0584,  0.9565,  1.8429,  0.9854,  1.2004,
          2.2212,  2.7480,  2.8424,  1.2917,  1.3552,  1.3169,  1.2163,  1.1138,
          0.9913,  0.8628,  0.7911,  0.8203,  0.9186,  1.0554,  1.2350,  1.3441],
        [-0.5803, -0.5878, -0.6036, -0.6306, -0.6559, -0.6533, -0.6780, -0.7169,
         -0.7180, -0.7023, -0.6605, -0.6211, -1.0998, -1.4176, -1.7279, -1.8638,
         -1.9343, -1.9770, -1.9745, -1.9514, -1.9665, -1.8566, -1.5497, -1.1813],
        [-0.0310, -0.0191, -0.0600, -0.4198, -0.6475, -0.6964, -0.7163, -0.7758,
         -0.7768, -0.7247, -0.5585, -0.3048,  0.3910,  0.5170,  0.6746,  0.7840,
          0.8718,  0.9209,  0.9274,  0.8948,  0.8189,  0.7498,  0.6248,  0.4531],
        [-0.5338, -0.4538, -0.1053,  0.5535,  1.5859,  1.0567,  1.0548,  1.6257,
          2.7750,  1.4205, -0.3427, -0.5848,  1.5236,  1.5355,  1.4541,  1.3222,
          1.1659,  1.0155,  0.9192,  0.9279,  1.0183,  1.1947,  1.4258,  1.4946],
        [-0.5575, -0.5720, -0.5867, -0.6054, -0.6344, -0.6337, -0.6599, -0.7053,
         -0.6917, -0.6702, -0.6408, -0.6043, -0.8457, -1.1353, -1.4141, -1.5592,
         -1.6336, -1.6868, -1.7122, -1.7071, -1.6565, -1.5509, -1.2663, -0.9240],
        [ 0.4541,  0.3421,  0.3157,  0.4117,  0.5629,  0.5553,  0.5813,  0.4753,
          0.5915,  0.8026,  0.6565,  0.5849, -0.3712, -0.2053,  0.0421,  0.2228,
          0.3876,  0.4673,  0.5185,  0.5098,  0.4417,  0.3146,  0.1246, -0.1900],
        [-0.5524, -0.4882, -0.3869, -0.3567, -0.4638, -0.5467, -0.5002, -0.4721,
         -0.5551, -0.5220, -0.5555, -0.5566, -0.7447, -0.9526, -1.1787, -1.2912,
         -1.3793, -1.4568, -1.4809, -1.4774, -1.4159, -1.3260, -1.0957, -0.8237],
        [-0.0944, -0.1754, -0.2919, -0.1391,  0.0612,  0.1248,  0.2870,  0.0337,
          0.1245,  0.1281,  0.1358,  0.0486, -0.3712, -0.1832,  0.0887,  0.3075,
          0.4605,  0.4952,  0.5267,  0.4663,  0.3572,  0.2045, -0.0113, -0.2558],
        [ 0.0138, -0.0749, -0.1258, -0.1235,  0.0519,  0.2062,  0.2480,  0.1747,
          0.1435,  0.2675,  0.2378,  0.1122,  0.1461,  0.2209,  0.3338,  0.4427,
          0.5026,  0.5103,  0.5453,  0.5553,  0.4829,  0.4075,  0.3154,  0.1896],
        [-0.5515, -0.5534, -0.5796, -0.5908, -0.6130, -0.4824, -0.2905, -0.3838,
         -0.4564, -0.4869, -0.5575, -0.5548, -1.0049, -0.9194, -0.6811, -0.4575,
         -0.1343,  0.1835,  0.3656,  0.2883,  0.1209, -0.1549, -0.5607, -0.8644],
        [-0.3335, -0.3579, -0.3887, -0.1070,  0.1023,  0.2485,  0.2935,  0.2816,
          0.1562,  0.0696,  0.0348, -0.1502, -0.4814, -0.2690,  0.0445,  0.2755,
          0.4097,  0.5296,  0.5701,  0.5119,  0.3615,  0.2021, -0.1241, -0.4158]]), tensor([[0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.]])]
[tensor([[-5.2788e-01, -5.4034e-01, -4.8549e-01, -3.0130e-01,  2.5707e-01,
          5.3091e-01,  6.1885e-01,  1.1059e+00,  1.7701e-01, -1.3701e-01,
         -3.6921e-01, -5.0003e-01, -4.6307e-01, -1.7490e-01,  1.6956e-01,
          4.3810e-01,  5.7331e-01,  6.4355e-01,  6.9818e-01,  6.8989e-01,
          5.7612e-01,  3.9035e-01,  3.1372e-03, -4.1897e-01],
        [ 3.7955e+00,  4.1382e+00,  3.9165e+00,  2.6421e+00,  4.8461e-01,
         -4.7830e-01, -6.3970e-01, -5.2637e-01,  4.4848e-01,  1.9829e+00,
          2.5865e+00,  3.3758e+00,  1.5297e+00,  1.4414e+00,  1.2850e+00,
          1.1321e+00,  1.0112e+00,  9.0797e-01,  8.6342e-01,  9.2172e-01,
          1.0313e+00,  1.1996e+00,  1.4229e+00,  1.5354e+00],
        [-4.8224e-01, -5.3197e-01, -5.9119e-01, -5.7427e-01, -6.1949e-01,
         -5.1329e-01, -4.1272e-01, -3.9545e-01, -3.0441e-01, -5.4345e-01,
         -4.9963e-01, -4.2493e-01, -1.2834e+00, -1.1104e+00, -1.0047e+00,
         -7.6211e-01, -4.6158e-01, -2.6581e-01, -1.8997e-01, -2.5195e-01,
         -4.4917e-01, -7.4167e-01, -1.0263e+00, -1.2377e+00],
        [-1.3238e-01, -9.3529e-02,  7.3195e-02, -4.3827e-01, -4.9920e-01,
         -4.5063e-01, -4.6476e-01, -3.6369e-01, -3.1074e-01, -2.5787e-01,
         -1.8975e-01, -2.0671e-01, -1.4181e+00, -1.2128e+00, -1.0978e+00,
         -8.3998e-01, -5.7214e-01, -4.0340e-01, -3.2629e-01, -3.8650e-01,
         -6.0957e-01, -9.4215e-01, -1.2692e+00, -1.4354e+00],
        [-6.0224e-01, -6.2319e-01, -6.5780e-01, -7.0443e-01, -7.3139e-01,
         -7.0211e-01, -7.2139e-01, -7.7659e-01, -7.7768e-01, -7.6275e-01,
         -6.8988e-01, -6.3255e-01,  8.8380e-01,  9.6262e-01,  1.0055e+00,
          1.0428e+00,  1.0620e+00,  1.0391e+00,  1.0059e+00,  1.0335e+00,
          1.0573e+00,  1.0700e+00,  1.0297e+00,  9.1429e-01],
        [-3.8168e-01, -4.5563e-01, -5.0148e-01, -5.6552e-01, -5.2344e-01,
         -2.0402e-01,  3.1140e-02, -9.4879e-02, -2.6912e-01, -3.7678e-01,
         -3.0645e-01, -3.8783e-01, -1.3538e+00, -1.0661e+00, -6.4678e-01,
         -3.0401e-01,  5.8079e-02,  3.1033e-01,  3.6151e-01,  2.5519e-01,
          8.6236e-02, -3.2847e-01, -9.0772e-01, -1.3664e+00],
        [-3.8083e-01, -4.8356e-01, -5.3967e-01, -4.3341e-01, -2.2224e-01,
         -1.6017e-02,  2.7042e-01,  1.6076e-01, -9.5374e-02, -3.7970e-01,
         -1.4856e-01, -1.6077e-01, -6.6817e-01, -4.4059e-01, -1.1481e-01,
          1.3805e-01,  2.7036e-01,  4.1997e-01,  4.9576e-01,  4.8289e-01,
          3.3551e-01,  1.2140e-01, -2.3108e-01, -5.6328e-01],
        [-5.7520e-01, -5.8316e-01, -6.0096e-01, -6.2672e-01, -6.5306e-01,
         -6.5003e-01, -6.7440e-01, -7.2236e-01, -7.1252e-01, -6.9452e-01,
         -6.5458e-01, -6.1665e-01, -1.0569e+00, -1.3788e+00, -1.6911e+00,
         -1.8249e+00, -1.8989e+00, -1.9405e+00, -1.9394e+00, -1.9183e+00,
         -1.9296e+00, -1.8223e+00, -1.5063e+00, -1.1311e+00],
        [-5.7013e-01, -5.4965e-01, -4.9970e-01, -2.9062e-01, -1.8494e-01,
          1.2071e-01,  8.3427e-01,  8.0761e-01,  1.7881e-01, -2.9685e-01,
         -4.7218e-01, -5.9191e-01, -1.0493e-01,  1.5999e-01,  3.9265e-01,
          5.3430e-01,  6.3744e-01,  6.7579e-01,  6.7959e-01,  6.5263e-01,
          5.6528e-01,  4.3435e-01,  2.0266e-01, -6.4480e-02],
        [-2.2365e-01, -2.2199e-01, -1.3909e-01, -1.2353e-01,  5.5649e-02,
          2.8919e-01,  1.1789e-01,  2.7851e-01,  1.1276e-01, -2.0045e-02,
          1.9270e-01,  2.0341e-02, -5.3042e-01, -3.3819e-01,  4.6989e-02,
          2.2509e-01,  3.9420e-01,  5.4466e-01,  5.9078e-01,  4.9738e-01,
          3.6803e-01,  1.9230e-01, -1.8193e-01, -4.5975e-01],
        [-2.9717e-01, -2.2757e-01, -5.2901e-01, -5.4901e-01, -3.1549e-01,
         -4.1726e-01, -3.7585e-01, -8.0934e-02, -1.6053e-01, -4.3136e-01,
         -1.8190e-01, -1.3604e-01, -1.0722e+00, -9.5261e-01, -7.3258e-01,
         -4.8038e-01, -2.3160e-01, -7.8400e-03,  1.0952e-01,  1.2271e-01,
          1.2537e-02, -2.5023e-01, -6.6482e-01, -9.8365e-01],
        [-1.6872e-01, -1.0377e-01, -1.7817e-01, -3.9553e-01, -6.6891e-01,
         -6.8014e-01, -7.1199e-01, -7.6729e-01, -7.5867e-01, -6.7698e-01,
         -5.9966e-01, -4.1875e-01,  1.7317e+00,  1.6047e+00,  1.3463e+00,
          1.0245e+00,  7.2589e-01,  4.7156e-01,  4.2141e-01,  5.1394e-01,
          7.5603e-01,  1.0749e+00,  1.4258e+00,  1.6923e+00],
        [ 2.3111e-02,  1.6153e-01, -1.0445e-01, -3.8581e-01, -5.4862e-01,
         -6.2642e-01, -6.2669e-01, -6.5806e-01, -5.8312e-01, -4.1089e-01,
         -2.5643e-01, -1.8198e-01,  1.4899e+00,  1.3390e+00,  1.0742e+00,
          7.5419e-01,  4.7159e-01,  2.3939e-01,  1.9421e-01,  2.9866e-01,
          4.8941e-01,  7.8154e-01,  1.1366e+00,  1.4194e+00],
        [-4.8985e-01, -4.9380e-01, -4.3486e-01, -1.7988e-01,  3.2235e-01,
          5.0730e-01,  4.5981e-01,  8.7656e-01,  5.6159e-01,  3.5512e-02,
         -2.6918e-01, -4.7618e-01, -7.4469e-01, -4.1015e-01,  5.3138e-03,
          3.3045e-01,  4.7823e-01,  5.5755e-01,  6.3622e-01,  6.4849e-01,

## Building a pytorch model
The next step is build a class to encapsulate the architecture of the ML model that we are going to train. As with the dataset, we do this by


### Further reading
- [Classification tutorial - Pytorch docs](https://docs.pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html)
- [Classification tutorial - Machine Learning Mastery](https://machinelearningmastery.com/building-a-multiclass-classification-model-in-pytorch/ )

In [33]:
class ClimateZoneClassifier(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = torch.nn.Linear(24, 60)
        self.act1 = torch.nn.ReLU()
        self.layer2 = torch.nn.Linear(60, 60)
        self.act2 = torch.nn.ReLU()
        self.layer3 = torch.nn.Linear(60, 60)
        self.act3 = torch.nn.ReLU()
        self.output = torch.nn.Linear(60, 5)
        self.sigmoid = torch.nn.Sigmoid()
        self.lsm = torch.nn.Softmax(dim=-1)
 
    def forward(self, x):
        x = self.act1(self.layer1(x))
        x = self.act2(self.layer2(x))
        x = self.act3(self.layer3(x))
        # x = self.sigmoid(self.output(x))
        x = self.lsm(self.output(x))
        return x

In [34]:
cz_classifier = ClimateZoneClassifier().to(device)

In [35]:
cz_classifier(cz_train_ds[:10][0].to(device))

tensor([[0.2265, 0.2168, 0.1832, 0.1801, 0.1935],
        [0.2267, 0.2167, 0.1832, 0.1802, 0.1931],
        [0.2268, 0.2166, 0.1834, 0.1802, 0.1930],
        [0.2269, 0.2166, 0.1834, 0.1802, 0.1929],
        [0.2271, 0.2165, 0.1834, 0.1802, 0.1928],
        [0.2267, 0.2163, 0.1838, 0.1801, 0.1931],
        [0.2260, 0.2162, 0.1843, 0.1799, 0.1935],
        [0.2251, 0.2161, 0.1848, 0.1799, 0.1941],
        [0.2251, 0.2160, 0.1849, 0.1798, 0.1941],
        [0.2246, 0.2159, 0.1853, 0.1797, 0.1945]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)

In [36]:
loss_fn = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(cz_classifier.parameters(), 
                             lr=training_params['learning_rate'])

### Experiment tracking with mlflow
In a project to develop a machine learning model, we are likely to train many different models as part of our epxerimentation, with different prdictors, hyperparameters, architectures and other experimental choices that we vary to understand the problem and find the best solution. We will ave a collection of different models, and to properly asses our experiments we need to know exactly which set of choices go with which model. Experiment tracking tools log all the elements of a training run together so they can be retrieved and analysed later. A common tool for this is **ML Flow**.

Further Reading
- [ML Flow docs](https://mlflow.org/)
- [Tracking pytorch with mlflow](https://mlflow.org/docs/latest/ml/deep-learning/pytorch/)

In [37]:
import mlflow

In [38]:
try:
    mlflow_port = os.environ['MLFLOW_PORT']
except KeyError:
    mlflow_port = 4455    
mlflow_server_uri = f'http://localhost:{mlflow_port}'

In [39]:
print(f'connecting to mlflow server {mlflow_server_uri}')
mlflow.set_tracking_uri(mlflow_server_uri)

connecting to mlflow server http://localhost:4455

In [40]:
mlflow.pytorch.autolog()

In [41]:
exp_name='climate_zones_torch_nn'

In [44]:
if mlflow.get_experiment_by_name(exp_name) is None:
    exp_id = mlflow.create_experiment(exp_name)
exp1 = mlflow.get_experiment_by_name(exp_name)
exp1

In [45]:
cz_signature = mlflow.models.infer_signature(cz_train_ds[:5][0].numpy(), cz_train_ds[:5][1].numpy())

## Run the training loop

In pytorch, we will explcitly define a loop which cycles through the data and updates the weights of the network to produce better predictions, which is to say predictions that are closer to the target data provided. Key steps in the training loop are:

- Iterate through the full data set for the number of epochs specified. An epopch is one full pass through the data.
- In each epoch, divide the dataset into minibatches. This is a set of data for which one will do graident descent.
- For each minibatch, do the follwing steps:
  -  Do a forward pass, or inference step to make predictions with the current weights. At the start of the process these will essentially be nonsense, but as we refine the weights the performance improves.
  -  Calculate the loss or error of the predictions.
  -  Do back propogation to update the weights towards weights that would produce correct predictions. This is done by calculating the gradient in the weights and moving the weights The amount one updates the weight is based on the learning rate.
  -  Update the weights based on the calculated gradients.

### Further reading
- [Training a model - pytorch docs](https://docs.pytorch.org/tutorials/beginner/introyt/trainingyt.html)
- [ Introduction to NNs - Kaggle](https://www.kaggle.com/code/carlosaguayo/introduction-to-neural-networks/notebook)
- [Tutorial on NNs for weather](https://github.com/MetOffice/ml_weather_tutorial/blob/main/03_algorithm_selection.ipynb)

In [67]:
def get_classification_metrics(model, cz_data, set_label, target_encoder):
    class_labels = target_encoder.classes_
    return pandas.DataFrame({
        'climate_group': class_labels,
        f'precision_{set_label}': sklearn.metrics.precision_score(
            target_encoder.inverse_transform(model(cz_data._X.to(device)).to('cpu').detach().numpy()),
            target_encoder.inverse_transform(cz_data._y.numpy()),
            average=None,
            labels=class_labels,
        ),
        f'recall_{set_label}': sklearn.metrics.recall_score(
            target_encoder.inverse_transform(model(cz_data._X.to(device)).to('cpu').detach().numpy()),
            target_encoder.inverse_transform(cz_data._y.numpy()),
            average=None,
            labels=class_labels,
        ),
    })

In [47]:
num_epochs = training_params['num_epochs']
# num_epochs = 1 # for debug

In [48]:
%%time
with mlflow.start_run(experiment_id=exp1.experiment_id) as current_run:
    print(current_run.info.run_id)
    mlflow.log_params(training_params)    
    mlflow.log_dict(cz_train_ds.stats_dict, 'stats.json')
    for epoch in range(num_epochs):
        print(f'epoch {epoch}')
        cz_classifier.train()
        epoch_loss_train = 0.0
        for batch_X, batch_y in cz_train_loader:
            optimizer.zero_grad()
            predictions = cz_classifier(batch_X.to(device))
            loss = loss_fn(predictions, batch_y.to(device))
            loss.backward()
            optimizer.step()
            epoch_loss_train += loss.to('cpu').item()

        #divide by number of batches
        epoch_loss_train /= len(cz_train_loader)
        
        epoch_loss_val = 0.0
        for X_val, y_val in cz_val_loader:
            epoch_loss_val += loss_fn(cz_classifier(X_val.to(device)), y_val.to(device)).item()    
        epoch_loss_val /= len(cz_val_loader)

        mlflow.log_metrics(
            { 'cross_entropy_train': epoch_loss_train,
            'cross_entropy_val': epoch_loss_val, },
            step=epoch,
        )
            
    metrics_df = get_classification_metrics(cz_classifier,
                                               cz_train_ds, 
                                               'train', 
                                               target_encoder=cz_train_ds.target_encoder)
    
    metrics_df = metrics_df.merge( get_classification_metrics(cz_classifier,
                                               cz_val_ds, 
                                               'val', 
                                               target_encoder=cz_train_ds.target_encoder), on='climate_group')
    mlflow.log_table(metrics_df, 'metrics.json')
        
    torch.save(cz_classifier,'cz_model.pth')
    mlflow.log_artifact('cz_model.pth')
    
    # mlflow.pytorch.log_model(cz_classifier,
    #                      name='climate_zones_classifier_torch', 
    #                      # signature=cz_signature, 
    #                      # input_example = cz_train_ds[:5][0].numpy(),
    #                      # export_model=True,
    #                     )

c8474e1b1dc849cbb9736e30f5e12501
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
🏃 View run upset-mouse-812 at: http://localhost:4455/#/experiments/2/runs/c8474e1b1dc849cbb9736e30f5e12501
🧪 View experiment at: http://localhost:4455/#/experiments/2
CPU times: user 6min 51s, sys: 1min, total: 7min 51s
Wall time: 12min 6s

### Load model and do inference

In [49]:
mlflow.search_runs(exp1.experiment_id)

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.cross_entropy_val,metrics.cross_entropy_train,params.criterion,params.batch_size,params.learning_rate,params.loss,params.optimizer,params.num_epochs,tags.mlflow.loggedArtifacts,tags.mlflow.source.name,tags.mlflow.source.type,tags.mlflow.user,tags.mlflow.runName
0,c8474e1b1dc849cbb9736e30f5e12501,2,FINISHED,mlflow-artifacts:/2/c8474e1b1dc849cbb9736e30f5...,2026-03-11 12:13:26.866000+00:00,2026-03-11 12:25:31.838000+00:00,0.942017,0.933169,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,"[{""path"": ""metrics.json"", ""type"": ""table""}]",/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,upset-mouse-812
1,58c2e476c4ac4fb596d4d7d5ec512ab9,2,FINISHED,mlflow-artifacts:/2/58c2e476c4ac4fb596d4d7d5ec...,2026-03-10 16:31:47.987000+00:00,2026-03-10 16:39:41.263000+00:00,0.938988,0.935487,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,"[{""path"": ""metrics.json"", ""type"": ""table""}]",/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,beautiful-mule-483
2,b14c877d8b554923be684b9ea4f8f208,2,FINISHED,mlflow-artifacts:/2/b14c877d8b554923be684b9ea4...,2026-03-10 15:57:49.618000+00:00,2026-03-10 15:58:40.695000+00:00,0.939722,0.953279,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,"[{""path"": ""metrics.json"", ""type"": ""table""}]",/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,gaudy-horse-269
3,516bda90a6f4427ab3d00ef436f59ad9,2,FINISHED,mlflow-artifacts:/2/516bda90a6f4427ab3d00ef436...,2026-03-10 15:51:21.018000+00:00,2026-03-10 15:51:30.622000+00:00,1.607479,0.000079,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,"[{""path"": ""metrics.json"", ""type"": ""table""}]",/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,brawny-goose-26
4,966179ca949c4063b2586b994cf20972,2,FINISHED,mlflow-artifacts:/2/966179ca949c4063b2586b994c...,2026-03-10 15:28:24.955000+00:00,2026-03-10 15:28:28.743000+00:00,1.602723,0.000079,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,powerful-vole-487
5,27afb603647c438c80b0b9451953ac2c,2,FAILED,mlflow-artifacts:/2/27afb603647c438c80b0b94519...,2026-03-10 15:28:02.614000+00:00,2026-03-10 15:28:06.283000+00:00,1.599319,0.000079,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,merciful-mole-906
6,c6bbb1a41eec4e0db3ae39847462f8f4,2,FINISHED,mlflow-artifacts:/2/c6bbb1a41eec4e0db3ae398474...,2026-03-10 14:58:22.192000+00:00,2026-03-10 14:59:10.661000+00:00,1.612314,0.000079,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,stately-finch-140
7,cc87b94f565d4e988c77708d351d7a8c,2,FAILED,mlflow-artifacts:/2/cc87b94f565d4e988c77708d35...,2026-03-10 14:55:08.911000+00:00,2026-03-10 14:55:10.633000+00:00,NaN,NaN,None,None,None,None,None,None,None,/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,chill-shoat-369
8,7162b267d38b4024828044a25298e156,2,FINISHED,mlflow-artifacts:/2/7162b267d38b4024828044a252...,2026-03-10 14:49:43.795000+00:00,2026-03-10 14:51:10.898000+00:00,1.606192,0.000079,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,"[{""path"": ""metrics.json"", ""type"": ""table""}]",/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,unruly-fowl-893
9,74b0917762174e46a662303343fa9c50,2,FAILED,mlflow-artifacts:/2/74b0917762174e46a662303343...,2026-03-10 14:49:11.318000+00:00,2026-03-10 14:49:16.712000+00:00,1.606165,0.000079,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,whimsical-hen-702
10,1150f44e0ef24e869ba751196c6c4f5f,2,FAILED,mlflow-artifacts:/2/1150f44e0ef24e869ba751196c...,2026-03-10 14:41:33.838000+00:00,2026-03-10 14:43:30.393000+00:00,0.941695,0.952503,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,honorable-bug-884
11,248d4615f9644500839e217899e6db0f,2,FAILED,mlflow-artifacts:/2/248d4615f9644500839e217899...,2026-03-10 14:37:15.838000+00:00,2026-03-10 14:39:17.249000+00:00,0.947812,0.953321,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,stately-flea-59
12,28433e4c6e2c4f59a935bbf5be051a11,2,FAILED,mlflow-artifacts:/2/28433e4c6e2c4f59a935bbf5be...,2026-03-10 14:34:10.148000+00:00,2026-03-10 14:36:38.804000+00:00,0.941281,0.952731,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,amazing-cat-91
13,cfb78b6677be45ed952f1fa04a2b5d32,2,FAILED,mlflow-artifacts:/2/cfb78b6677be45ed952f1fa04a...,2026-03-10 14:33:34.516000+00:00,2026-03-10 14:33:35.609000+00:00,NaN,NaN,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,marvelous-sloth-431
14,5623c8faa20541a4a2e745bf32496e83,2,FAILED,mlflow-artifacts:/2/5623c8faa20541a4a2e745bf32...,2026-03-10 14:29:13.390000+00:00,2026-03-10 14:31:30.579000+00:00,0.950783,0.954181,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,adaptable-mink-204
15,42bfc7d1a5ea489597b806c29b1200ad,2,FAILED,mlflow-artifacts:/2/42bfc7d1a5ea489597b806c29b...,2026-03-10 11:58:19.420000+00:00,2026-03-10 12:07:46.440000+00:00,0.933366,0.932371,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/gws/nopw/j04/mohc_shared/users/shaddad/venv/a...,NOTEBOOK,shaddad,puzzled-smelt-907
16,f1802f7630a54a479aa9f5669d9202f5,2,FAILED,mlflow-artifacts:/2/f1802f7630a54a479aa9f5669d...,2026-03-06 14:35:31.133000+00:00,2026-03-06 14:43:41.474000+00:00,0.934594,0.935833,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/home/users/shaddad/mohc_user/venv/ai4c_nb_gpu...,NOTEBOOK,shaddad,selective-pig-348
17,04167a386a3e417bb6358d993b80e3f3,2,FAILED,mlflow-artifacts:/2/04167a386a3e417bb6358d993b...,2026-03-06 14:28:30.045000+00:00,2026-03-06 14:29:17.495000+00:00,NaN,NaN,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/home/users/shaddad/mohc_user/venv/ai4c_nb_gpu...,NOTEBOOK,shaddad,burly-ox-804
18,fb6e482064d846ca876d9b16db59b4bc,2,FAILED,mlflow-artifacts:/2/fb6e482064d846ca876d9b16db...,2026-03-06 14:28:09.904000+00:00,2026-03-06 14:28:11.872000+00:00,NaN,NaN,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/home/users/shaddad/mohc_user/venv/ai4c_nb_gpu...,NOTEBOOK,shaddad,capable-crab-63
19,a5f50e1346ef4b6f9ed80f8925aee5df,2,FAILED,mlflow-artifacts:/2/a5f50e1346ef4b6f9ed80f8925...,2026-03-06 14:27:53.948000+00:00,2026-03-06 14:27:55.515000+00:00,NaN,NaN,CrossEntropyLoss,16,0.001,CrossEntropyLoss,Adam,10,None,/home/users/shaddad/mohc_user/venv/ai4c_nb_gpu...,NOTEBOOK,shaddad,smiling-mule-323
20,eb44d988c3d84f178c74db82df135654,2,FAILED,mlflow-artifacts:/2/eb44d988c3d84f178c74db82df...,2026-03-06 11:53:28.931000+00:00,2026-03-06 12:00:40.101000+00:00,NaN,NaN,None,16,0.001,None,None,10,None,/home/users/shaddad/mohc_user/venv/ai4c_nb_gpu...,NOTEBOOK,shaddad,bald-slug-255
21,209deb512be047798c491d23ddd8a25d,2,FAILED,mlflow-artifacts:/2/209deb512be047798c491d23dd...,2026-03-06 11:51:09.641000+00:00,2026-03-06 11:51:09.741000+00:00,NaN,NaN,None,16,0.001,None,None,10,None,/home/users/shaddad/mohc_user/venv/ai4c_nb_gpu...,NOTEBOOK,shaddad,awesome-grouse-516
22,d9d62b187a1b4ad585cc43650f197979,2,FAILED,mlflow-artifacts:/2/d9d62b187a1b4ad585cc43650f...,2026-03-06 11:15:54.772000+00:00,2026-03-06 11:15:55.272000+00:00,NaN,NaN,None,None,None,None,None,None,None,/home/users/shaddad/mohc_user/venv/ai4c_nb_gpu...,NOTEBOOK,shaddad,incongruous-auk-52

In [50]:
model_inference = torch.load('cz_model.pth', weights_only=False)

In [51]:
model_inference

ClimateZoneClassifier(
  (layer1): Linear(in_features=24, out_features=60, bias=True)
  (act1): ReLU()
  (layer2): Linear(in_features=60, out_features=60, bias=True)
  (act2): ReLU()
  (layer3): Linear(in_features=60, out_features=60, bias=True)
  (act3): ReLU()
  (output): Linear(in_features=60, out_features=5, bias=True)
  (sigmoid): Sigmoid()
  (lsm): Softmax(dim=-1)
)

In [55]:
cz_train_ds.target_encoder.inverse_transform(
    model_inference(cz_val_ds._X.to(device)).to('cpu').detach().numpy()
)

array(['A', 'B', 'E', ..., 'E', 'C', 'D'], shape=(40644,), dtype='<U1')

### Evaluation

We will go into more details on evaluating the performance of a machine learning model in a separate notebook.

In [ ]:
# load metrics from mlflow to see training

In [58]:
metrics_path = pathlib.Path(mlflow.artifacts.download_artifacts('runs:/c8474e1b1dc849cbb9736e30f5e12501/metrics.json'))
metrics_path

PosixPath('/tmp/tmpmnydw_35/metrics.json')

In [59]:
with open(metrics_path) as metrics_file:
    metrics_mlflow_dict = json.load(metrics_file)
metrics_mlflow_dict

{'columns': ['climate_group',
  'precision_train',
  'recall_train',
  'precision_val',
  'recall_val'],
 'data': [['A', 0.9891433966, 0.945634619, 0.9885804292, 0.9434423149],
  ['B', 0.9360421122, 0.986016046, 0.9343065693, 0.9875998898],
  ['C', 0.8379201526, 0.9585274735, 0.8264364394, 0.9519890261],
  ['D', 0.9730827328, 0.939062276, 0.9724493769, 0.9355624239],
  ['E', 0.9943433265, 0.9797332836, 0.9931987099, 0.9788542602]]}

In [62]:
pandas.DataFrame(metrics_mlflow_dict['data'],columns=metrics_mlflow_dict['columns'])

  climate_group  precision_train  recall_train  precision_val  recall_val
0             A         0.989143      0.945635       0.988580    0.943442
1             B         0.936042      0.986016       0.934307    0.987600
2             C         0.837920      0.958527       0.826436    0.951989
3             D         0.973083      0.939062       0.972449    0.935562
4             E         0.994343      0.979733       0.993199    0.978854

In [ ]:
cal

In [ ]:
# calculate metrics from predictions on test vset

In [71]:
test_metrics_df = get_classification_metrics(cz_classifier,
                                             cz_test_ds, 
                                             'test', 
                                             target_encoder=cz_train_ds.target_encoder)
test_metrics_df

  climate_group  precision_test  recall_test
0             A        0.990693     0.948436
1             B        0.934833     0.986761
2             C        0.843255     0.952365
3             D        0.971295     0.939277
4             E        0.993372     0.978310

# Exercises

Once you have worked through the tutorial above, you can test your knowledge by adapting the code in the tutorial to experiment with different options for training the model and comparing results.

### Varying model architecture
Try to change the model architecture e.g. more layers

In [ ]:
# insert code here

### Next steps or potential follow on material

Links from notebook
- [pytorch docs](https://pytorch.org/)

Additional excercises in this tutorial material includes:
- Training a CNN autoencoder on CMIP6 data
- Training a RNN on Jena weather dataset for time series prediction.

### Data statement
This data used in this notebook is derived from the Koppen-Geiger Climate Cliassfication dataset created by GloH2O.

###     References
- [Climate Zones Dataset](https://www.gloh2o.org/koppen/#:~:text=The%20K%C3%B6ppen%2DGeiger%20climate%20classification%20maps%20are%20high%2Dresolution,Climate%20Sensitivity%20(ECS)%2C%20and%20historical%20warming%20trend)